Drop Ruby 1.9, switch to using Module.prepend instead of method aliasing
appsignal/appsignal-ruby pull request #676
Opened 2021-01-05 11:08 UTC by jeffkreeftmeijer

Part of Appsignal for Ruby 3.0. Closes #603.

2021-01-05 16:47 UTC, tombruijn requested changes
Found a couple of things. I haven't manually tested this yet.

2021-01-05 16:47 UTC, tombruijn commented on lib/appsignal/integrations/redis.rb
> +          process_without_appsignal(commands, &block)
```suggestion
          super
```

`process_without_appsignal` doesn't exist anymore.

2021-01-06 12:58 UTC, matsimitsu approved these changes

2021-01-08 13:07 UTC, xadamy commented
Removing myself from the reviewer list for this one, as it's unlikely I'll get round to reviewing it before I go on leave, unfortunately.

2021-01-08 15:52 UTC, tombruijn commented
@jeffkreeftmeijer can I help to get this merged? Fix the tests and such.

2021-01-11 06:44 UTC, jeffkreeftmeijer commented
@tombruijn that’d be great indeed!

2021-01-12 09:29 UTC, tombruijn commented
I continued this in #683 and only needs the fixes I suggested here in this pr before review.

2021-01-15 09:32 UTC, tombruijn commented
Closing this in favor of #683

2021-01-15 09:32 UTC, closed without merging